# Generated by Django 3.2.6 on 2022-11-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20221104_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default='Sanjeew', max_length=100),
            preserve_default=False,
        ),
    ]
